name: Generate stats card

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate stats.svg
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: "username=${{ github.repository_owner }}&hide_title=false&hide_rank=false&show_icons=true&include_all_commits=true&count_private=true&disable_animations=false&theme=dracula&locale=en&hide_border=false"
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true

      - name: Commit stats.svg
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/stats.svg
          git commit -m "Update stats card" || exit 0
          git push